// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwJUWjC0amRz7ODqiZrsYeHAdNnQiPKIQ',
    appId: '1:1004474865919:web:8351bfaffe316ef98254ca',
    messagingSenderId: '1004474865919',
    projectId: 'league-five-vs-five',
    authDomain: 'league-five-vs-five.firebaseapp.com',
    storageBucket: 'league-five-vs-five.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDucrd1ckAoLRqcZ8EStlOErwcn6b4fruo',
    appId: '1:1004474865919:android:acad5eef85a27ce88254ca',
    messagingSenderId: '1004474865919',
    projectId: 'league-five-vs-five',
    storageBucket: 'league-five-vs-five.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsSl2n1f3iBt7GOO3UFgERK6QU_FWbZgk',
    appId: '1:1004474865919:ios:da861fd33b8e262e8254ca',
    messagingSenderId: '1004474865919',
    projectId: 'league-five-vs-five',
    storageBucket: 'league-five-vs-five.appspot.com',
    iosClientId: '1004474865919-phqfpd773ooc8kq4lfso0hk3g355jri4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiveByFive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsSl2n1f3iBt7GOO3UFgERK6QU_FWbZgk',
    appId: '1:1004474865919:ios:da861fd33b8e262e8254ca',
    messagingSenderId: '1004474865919',
    projectId: 'league-five-vs-five',
    storageBucket: 'league-five-vs-five.appspot.com',
    iosClientId: '1004474865919-phqfpd773ooc8kq4lfso0hk3g355jri4.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiveByFive',
  );
}
